export const CHANNEL_TYPES = {
  0: {name: 'GUILD_TEXT', icon: '3280-text'},
  1: {name: 'DM', icon: '2885-discord-message-requests-white'},
  2: {name: 'GUILD_VOICE', icon: '7032-voice'},
  3: {name: 'GROUP_DM', icon: '8523-default-role-permissions'},
  4: {name: 'GUILD_CATEGORY', icon: '1821-servers-folder'},
  5: {name: 'GUILD_ANNOUNCEMENT', icon: '1697-discord-announcement-white'},
  10: {name: 'ANNOUNCEMENT_THREAD', icon: '8312-active-threads'},
  11: {name: 'PUBLIC_THREAD', icon: '8582-discord-thread-white'},
  12: {name: 'PRIVATE_THREAD', icon: '7589-discord-thread-private-white'},
  13: {name: 'GUILD_STAGE_VOICE', icon: '7969-stage'},
  14: {name: 'GUILD_DIRECTORY', icon: '9211-student-centers'},
  15: {name: 'GUILD_FORUM', icon: '5971-forum'},
  16: {name: 'GUILD_MEDIA', icon: '7361-media'},
};
